<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_DuocUC.svg/2560px-Logo_DuocUC.svg.png' width=50%, height=70%>

##En este Notebook revisaremos lo visto en clase sobre escalamiento de variables

In [1]:
import numpy as np
import pandas as pd

# Normalización y estandarización
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

### Usaremos el data set de: California Housing

In [2]:
# Puedes agregar la dirección que quieras, siempre y cuando haga referencia al dataset.
# Debes poner atención al separador. El parámetro "sep" indica como se separan los datos en el dataset.

url = "https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"
df_housing = pd.read_csv(url, sep=",")
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [3]:
# Algunas estadísticas básicas de solo las variables numéricas
df_housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [4]:
# Revisamos el tipo de datos
df_housing.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

#Estandarización

In [5]:
# Se crea primero el objeto Standard Scaler
scaler = StandardScaler()

# Luego "entrenamos" con los datos para obtener los parámetros del escalamiento
scaler.fit(df_housing)

# Finalmente aplicamos el escalamiento
array_scaler = scaler.transform(df_housing)
array_scaler

array([[ 2.619365  , -0.67152023, -1.07967114, ..., -0.07599796,
        -1.25254316, -1.21055773],
       [ 2.53956878, -0.57326437, -0.76187201, ..., -0.09940441,
        -1.08148298, -1.09674535],
       [ 2.4946834 , -0.90546278, -0.92077158, ..., -0.99925206,
        -1.17010515, -1.04846131],
       ...,
       [-2.36291168,  2.90780067, -0.92077158, ..., -0.11760942,
        -0.44666313, -0.89412482],
       [-2.36291168,  2.88908527, -0.76187201, ..., -0.06039367,
        -0.99778717, -1.04759909],
       [-2.387848  ,  2.29955006,  1.85997083, ..., -0.60134255,
        -0.45536288, -0.97172417]])

### Se ve que entraga los datos más "desordenados". Esto pasa por que lo que entrega es un arreglo (array). Lo pasaremos a DataFrame

In [6]:
df_standar_scaler = pd.DataFrame(array_scaler)
df_standar_scaler

,0,1,2,3,4,5,6,7,8
0,2.619365,-0.671520,-1.079671,1.361695,1.764204,-0.361184,-0.075998,-1.252543,-1.210558
1,2.539569,-0.573264,-0.761872,2.296608,3.230441,-0.261865,-0.099404,-1.081483,-1.096745
2,2.494683,-0.905463,-0.920772,-0.882462,-0.866956,-0.955354,-0.999252,-1.170105,-1.048461
3,2.489696,-0.928857,-1.159121,-0.524186,-0.480230,-0.796793,-0.715774,-0.362600,-1.154514
4,2.489696,-0.961609,-0.682422,-0.545747,-0.506328,-0.701830,-0.622148,-1.026454,-1.222629
...,...,...,...,...,...,...,...,...,...
16995,-2.342963,2.318265,1.859971,-0.195728,-0.344995,-0.455275,-0.343872,-0.799999,-0.826872
16996,-2.347950,2.369733,0.588774,-0.135174,-0.027073,-0.205236,-0.094203,-0.715727,-1.106230
16997,-2.362912,2.907801,-0.920772,0.015292,-0.019955,-0.161675,-0.117609,-0.446663,-0.894125
16998,-2.362912,2.889085,-0.761872,0.012999,0.029868,-0.114630,-0.060394,-0.997787,-1.047599
16999,-2.387848,2.299550,1.859971,-0.377848,-0.568015,-0.543268,-0.601343,-0.455363,-0.971724

**Ahora el problema es que las columnas perdieron sus nombres**

Podemos recuperar los nombres

In [7]:
df_standar_scaler.columns = df_housing.columns
df_standar_scaler

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,2.619365,-0.671520,-1.079671,1.361695,1.764204,-0.361184,-0.075998,-1.252543,-1.210558
1,2.539569,-0.573264,-0.761872,2.296608,3.230441,-0.261865,-0.099404,-1.081483,-1.096745
2,2.494683,-0.905463,-0.920772,-0.882462,-0.866956,-0.955354,-0.999252,-1.170105,-1.048461
3,2.489696,-0.928857,-1.159121,-0.524186,-0.480230,-0.796793,-0.715774,-0.362600,-1.154514
4,2.489696,-0.961609,-0.682422,-0.545747,-0.506328,-0.701830,-0.622148,-1.026454,-1.222629
...,...,...,...,...,...,...,...,...,...
16995,-2.342963,2.318265,1.859971,-0.195728,-0.344995,-0.455275,-0.343872,-0.799999,-0.826872
16996,-2.347950,2.369733,0.588774,-0.135174,-0.027073,-0.205236,-0.094203,-0.715727,-1.106230
16997,-2.362912,2.907801,-0.920772,0.015292,-0.019955,-0.161675,-0.117609,-0.446663,-0.894125
16998,-2.362912,2.889085,-0.761872,0.012999,0.029868,-0.114630,-0.060394,-0.997787,-1.047599
16999,-2.387848,2.299550,1.859971,-0.377848,-0.568015,-0.543268,-0.601343,-0.455363,-0.971724

Finalmente, corroboramos el resultado:

In [8]:
df_standar_scaler.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04,1.700000e+04
mean,-6.633961e-15,2.674984e-17,-7.606987e-17,-9.028072e-17,-8.693699e-17,7.356207e-17,2.006238e-17,-3.644666e-16,1.337492e-17
std,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00,1.000029e+00
min,-2.387848e+00,-1.443531e+00,-2.191968e+00,-1.211838e+00,-1.277408e+00,-1.242856e+00,-1.300935e+00,-1.773323e+00,-1.658056e+00
25%,-1.111108e+00,-7.931704e-01,-8.413218e-01,-5.420770e-01,-5.751323e-01,-5.572079e-01,-5.701340e-01,-6.903217e-01,-7.578949e-01
50%,5.346887e-01,-6.434471e-01,3.262582e-02,-2.370147e-01,-2.500927e-01,-2.287590e-01,-2.398431e-01,-1.776521e-01,-2.319437e-01
75%,7.790646e-01,9.801141e-01,6.682241e-01,2.328499e-01,2.582266e-01,2.538954e-01,2.705474e-01,4.629850e-01,4.974902e-01
max,2.619365e+00,2.959268e+00,1.859971e+00,1.619047e+01,1.401132e+01,2.984131e+01,1.451402e+01,5.825963e+00,2.523704e+00

### ¿Cómo sabemos que lo hizo bien?

# Normalización

In [9]:
# Se crea primero el objeto Standard Scaler
scaler = MinMaxScaler()

# Luego "entrenamos" con los datos para obtener los parámetros del escalamiento
scaler.fit(df_housing)

# Finalmente aplicamos el escalamiento
array_scaler = scaler.transform(df_housing)
array_scaler

array([[1.        , 0.17534538, 0.2745098 , ..., 0.07745437, 0.06853009,
        0.10701193],
       [0.98406375, 0.19766206, 0.35294118, ..., 0.07597435, 0.09104012,
        0.13422831],
       [0.9750996 , 0.12221041, 0.31372549, ..., 0.01907581, 0.07937822,
        0.14577466],
       ...,
       [0.00498008, 0.98831031, 0.31372549, ..., 0.07482322, 0.1745769 ,
        0.18268172],
       [0.00498008, 0.98405951, 0.35294118, ..., 0.07844105, 0.10205376,
        0.14598084],
       [0.        , 0.8501594 , 1.        , ..., 0.04423615, 0.17343209,
        0.1641251 ]])

In [10]:
df_norm_scaler = pd.DataFrame(array_scaler)
df_norm_scaler

,0,1,2,3,4,5,6,7,8
0,1.000000,0.175345,0.274510,0.147885,0.198945,0.028364,0.077454,0.068530,0.107012
1,0.984064,0.197662,0.352941,0.201608,0.294848,0.031559,0.075974,0.091040,0.134228
2,0.975100,0.122210,0.313725,0.018927,0.026847,0.009249,0.019076,0.079378,0.145775
3,0.974104,0.116897,0.254902,0.039515,0.052142,0.014350,0.037000,0.185639,0.120414
4,0.974104,0.109458,0.372549,0.038276,0.050435,0.017405,0.042921,0.098281,0.104125
...,...,...,...,...,...,...,...,...,...
16995,0.008964,0.854410,1.000000,0.058389,0.060987,0.025337,0.060516,0.128081,0.198764
16996,0.007968,0.866100,0.686275,0.061869,0.081782,0.033381,0.076303,0.139170,0.131960
16997,0.004980,0.988310,0.313725,0.070515,0.082247,0.034782,0.074823,0.174577,0.182682
16998,0.004980,0.984060,0.352941,0.070384,0.085506,0.036296,0.078441,0.102054,0.145981
16999,0.000000,0.850159,1.000000,0.047924,0.046400,0.022506,0.044236,0.173432,0.164125

In [11]:
df_norm_scaler.columns = df_housing.columns
df_norm_scaler

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,1.000000,0.175345,0.274510,0.147885,0.198945,0.028364,0.077454,0.068530,0.107012
1,0.984064,0.197662,0.352941,0.201608,0.294848,0.031559,0.075974,0.091040,0.134228
2,0.975100,0.122210,0.313725,0.018927,0.026847,0.009249,0.019076,0.079378,0.145775
3,0.974104,0.116897,0.254902,0.039515,0.052142,0.014350,0.037000,0.185639,0.120414
4,0.974104,0.109458,0.372549,0.038276,0.050435,0.017405,0.042921,0.098281,0.104125
...,...,...,...,...,...,...,...,...,...
16995,0.008964,0.854410,1.000000,0.058389,0.060987,0.025337,0.060516,0.128081,0.198764
16996,0.007968,0.866100,0.686275,0.061869,0.081782,0.033381,0.076303,0.139170,0.131960
16997,0.004980,0.988310,0.313725,0.070515,0.082247,0.034782,0.074823,0.174577,0.182682
16998,0.004980,0.984060,0.352941,0.070384,0.085506,0.036296,0.078441,0.102054,0.145981
16999,0.000000,0.850159,1.000000,0.047924,0.046400,0.022506,0.044236,0.173432,0.164125

In [12]:
df_norm_scaler.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,0.476882,0.327867,0.540968,0.069637,0.083552,0.039984,0.082260,0.233354,0.396497
std,0.199718,0.227135,0.246803,0.057465,0.065410,0.032172,0.063233,0.131595,0.239141
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.254980,0.147715,0.333333,0.038487,0.045934,0.022058,0.046210,0.142514,0.215259
50%,0.583665,0.181722,0.549020,0.056017,0.067194,0.032624,0.067094,0.209976,0.341032
75%,0.632470,0.550478,0.705882,0.083017,0.100442,0.048152,0.099367,0.294279,0.515464
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

###Los métodos para escalar tienen las funciones inversas. Esto quiere decir que, se puede volver a la escala original de los datos.


```
# inverse.transform(X)
```

###Esto es muy importante cuando trabajamos con algoritmos de ML. ¿Por qué podría ser importante?

#Escalamiento Robusto

In [13]:
robust_scaler = RobustScaler()
array_scaler = robust_scaler.fit_transform(df_housing)
df_robust_scaler = pd.DataFrame(array_scaler)
df_robust_scaler

,0,1,2,3,4,5,6,7,8
0,1.102902,-0.015831,-0.736842,2.063046,2.417082,-0.163265,0.194896,-0.932008,-0.779533
1,1.060686,0.039578,-0.526316,3.269498,4.176512,-0.040816,0.167053,-0.783686,-0.688874
2,1.036939,-0.147757,-0.631579,-0.832914,-0.740214,-0.895811,-0.903326,-0.860528,-0.650412
3,1.034301,-0.160950,-0.789474,-0.370579,-0.276157,-0.700322,-0.566125,-0.160364,-0.734890
4,1.034301,-0.179420,-0.473684,-0.398402,-0.307473,-0.583244,-0.454756,-0.735973,-0.789148
...,...,...,...,...,...,...,...,...,...
16995,-1.522427,1.670185,1.210526,0.053278,-0.113879,-0.279270,-0.123743,-0.539619,-0.473901
16996,-1.525066,1.699208,0.368421,0.131419,0.267616,0.029001,0.173241,-0.466549,-0.696429
16997,-1.532982,2.002639,-0.631579,0.325588,0.276157,0.082707,0.145398,-0.233252,-0.527473
16998,-1.532982,1.992084,-0.526316,0.322628,0.335943,0.140709,0.213457,-0.711116,-0.649725
16999,-1.546174,1.659631,1.210526,-0.181737,-0.381495,-0.387755,-0.430008,-0.240795,-0.589286

In [14]:
df_robust_scaler.columns = df_housing.columns
df_robust_scaler

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,1.102902,-0.015831,-0.736842,2.063046,2.417082,-0.163265,0.194896,-0.932008,-0.779533
1,1.060686,0.039578,-0.526316,3.269498,4.176512,-0.040816,0.167053,-0.783686,-0.688874
2,1.036939,-0.147757,-0.631579,-0.832914,-0.740214,-0.895811,-0.903326,-0.860528,-0.650412
3,1.034301,-0.160950,-0.789474,-0.370579,-0.276157,-0.700322,-0.566125,-0.160364,-0.734890
4,1.034301,-0.179420,-0.473684,-0.398402,-0.307473,-0.583244,-0.454756,-0.735973,-0.789148
...,...,...,...,...,...,...,...,...,...
16995,-1.522427,1.670185,1.210526,0.053278,-0.113879,-0.279270,-0.123743,-0.539619,-0.473901
16996,-1.525066,1.699208,0.368421,0.131419,0.267616,0.029001,0.173241,-0.466549,-0.696429
16997,-1.532982,2.002639,-0.631579,0.325588,0.276157,0.082707,0.145398,-0.233252,-0.527473
16998,-1.532982,1.992084,-0.526316,0.322628,0.335943,0.140709,0.213457,-0.711116,-0.649725
16999,-1.546174,1.659631,1.210526,-0.181737,-0.381495,-0.387755,-0.430008,-0.240795,-0.589286

In [15]:
df_robust_scaler.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-0.282878,0.362856,-0.021613,0.305854,0.300102,0.282034,0.285296,0.154037,0.184759
std,0.529068,0.563942,0.662470,1.290482,1.199998,1.232925,1.189546,0.867098,0.796592
min,-1.546174,-0.451187,-1.473684,-1.257955,-1.232740,-1.250269,-1.262181,-1.383561,-1.135996
25%,-0.870712,-0.084433,-0.578947,-0.393666,-0.390036,-0.404941,-0.392885,-0.444521,-0.418956
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.129288,0.915567,0.421053,0.606334,0.609964,0.595059,0.607115,0.555479,0.581044
max,1.102902,2.031662,1.210526,21.198757,17.113167,37.073040,17.549884,5.205567,2.195062

#Ahora revisaremos lo visto en clase sobre encoding de variables categóricas

In [16]:
import numpy as np
import pandas as pd

# Encodeo
from sklearn import preprocessing

In [17]:
datos = {'alumno': ['Alejandro', 'Pedro', 'Sofia','Leonora' ,'Sergio', 'Maria'],
         'Primera prueba': [7, 8,7,7,8.5, 10],
         'Segunda prueba': [10,9,10,4,10,6.7],
         'Sexo':['Masculino','Masculino','Femenino','Femenino','Masculino','Femenino'],
         'Pais':['Chile', 'Chile', 'Peru', 'Brasil', 'Brasil','Chile'],
         'Año' :['Segundo', 'Tercero', 'Segundo', 'Primero', 'Tercero', 'Tercero']}
df = pd.DataFrame(datos)
df

      alumno  Primera prueba  Segunda prueba       Sexo    Pais      Año
0  Alejandro             7.0            10.0  Masculino   Chile  Segundo
1      Pedro             8.0             9.0  Masculino   Chile  Tercero
2      Sofia             7.0            10.0   Femenino    Peru  Segundo
3    Leonora             7.0             4.0   Femenino  Brasil  Primero
4     Sergio             8.5            10.0  Masculino  Brasil  Tercero
5      Maria            10.0             6.7   Femenino   Chile  Tercero

#Ordinal Encoder

Aplicaremos Ordinal encoder a la variable "año". Ya que nos importa preservar el orden, usaremos la función .replace(). Es muy sencillo hacerlo de esta manera.

In [18]:
# Usaremos la función replace, ya que es más facil.
df['Año'] = df['Año'].replace({'Primero': 1, 'Segundo': 2, 'Tercero': 3})
df

/tmp/ipython-input-3102116562.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Año'] = df['Año'].replace({'Primero': 1, 'Segundo': 2, 'Tercero': 3})

      alumno  Primera prueba  Segunda prueba       Sexo    Pais  Año
0  Alejandro             7.0            10.0  Masculino   Chile    2
1      Pedro             8.0             9.0  Masculino   Chile    3
2      Sofia             7.0            10.0   Femenino    Peru    2
3    Leonora             7.0             4.0   Femenino  Brasil    1
4     Sergio             8.5            10.0  Masculino  Brasil    3
5      Maria            10.0             6.7   Femenino   Chile    3

#One-Hot Encoder

Aplicaremos One-hot encoder a la variable categórica Sexo.

In [23]:
# Aplicar One-Hot Encoding usando get_dummies() de pandas
#data = df['Sexo']
ohe = pd.get_dummies(df, columns=['Sexo'])
ohe

      alumno  Primera prueba  Segunda prueba    Pais  Año  Sexo_0  Sexo_1
0  Alejandro             7.0            10.0   Chile    2    True   False
1      Pedro             8.0             9.0   Chile    3    True   False
2      Sofia             7.0            10.0    Peru    2   False    True
3    Leonora             7.0             4.0  Brasil    1   False    True
4     Sergio             8.5            10.0  Brasil    3    True   False
5      Maria            10.0             6.7   Chile    3   False    True

Como se puede observar, se crean 2 variables, una por cada valor de la variable "sexo". Pero estan deben tener valores numéricos. Por lo tanto, primero les daremos un valor numérico y luego aplicaremos un encoding del tipo One-hot

In [24]:
# Usaremos la función replace, ya que es más facil.
df['Sexo'] = df['Sexo'].replace({'Masculino': '0', 'Femenino': '1'})
df

      alumno  Primera prueba  Segunda prueba Sexo    Pais  Año
0  Alejandro             7.0            10.0    0   Chile    2
1      Pedro             8.0             9.0    0   Chile    3
2      Sofia             7.0            10.0    1    Peru    2
3    Leonora             7.0             4.0    1  Brasil    1
4     Sergio             8.5            10.0    0  Brasil    3
5      Maria            10.0             6.7    1   Chile    3

In [26]:
ohe = pd.get_dummies(df, columns=['Sexo'], dtype=int)
ohe

      alumno  Primera prueba  Segunda prueba    Pais  Año  Sexo_0  Sexo_1
0  Alejandro             7.0            10.0   Chile    2       1       0
1      Pedro             8.0             9.0   Chile    3       1       0
2      Sofia             7.0            10.0    Peru    2       0       1
3    Leonora             7.0             4.0  Brasil    1       0       1
4     Sergio             8.5            10.0  Brasil    3       1       0
5      Maria            10.0             6.7   Chile    3       0       1

Solo falta cambiar los nombres de las columnas. Esto es opcional.

In [27]:
ohe.columns = ['alumno','Primera prueba', 'Segunda prueba',	'Pais',	'Año', 'Masculino', 'Femenino']
ohe

      alumno  Primera prueba  Segunda prueba    Pais  Año  Masculino  Femenino
0  Alejandro             7.0            10.0   Chile    2          1         0
1      Pedro             8.0             9.0   Chile    3          1         0
2      Sofia             7.0            10.0    Peru    2          0         1
3    Leonora             7.0             4.0  Brasil    1          0         1
4     Sergio             8.5            10.0  Brasil    3          1         0
5      Maria            10.0             6.7   Chile    3          0         1

In [28]:
# Con esto revisamos el tipo de dato de las variables y corroboramos que sea numérico.
ohe.dtypes

alumno             object
Primera prueba    float64
Segunda prueba    float64
Pais               object
Año                 int64
Masculino           int64
Femenino            int64
dtype: object